### PR TITLE
Basic ASP.NET webforms project scaffolding.

### PR DESCRIPTION
**Pull request by Spawnbroker**
Hey there!  

I have been reading your blog about potentially writing a companion web application to go with your shop indexer.  I decided to begin development on an ASP.NET version of this app using Angular and ElasticSearch, with some basic bootstrap styling to start with.

I'm using C# and ASP.NET because those are what I'm familiar with as a developer.  I also have some experience with javascript, so using the Angular and ElasticSearch javascript libraries should be no problem.

I am developing using Visual Studio 2015, and I will eventually start hosting this on Windows Azure if multiple developers start contributing.  

Let me know what you think.

### CODE REVIEW

**Comment by trackpete** [comment]
I would love to see what this looks like up and running! I have zero experience at all with ASP.NET and windows based development/hosting, so I'm not even sure where to start. ;)

Do you have this hosted anywhere so we could check it out?

**Comment by Spawnbroker** [comment]
Sure, I just threw it up on a basic Azure website, you can navigate to it here:

poetradesearch.azurewebsites.net

It wasn't working 100% on the pull that I just did so I had to make some minor changes, so you can cancel this one and I can make another pull request if you like.  

There's really nothing there yet, it's just a basic starter project for anyone to begin working off of.

**Comment by Spawnbroker** [comment]
Oh, I guess we don't have to close pull requests if I commit after I start the request.

I'm still learning github, we use TFS at my job so I don't know all of the ins and outs.

**Comment by trackpete** [comment]
This might be my inexperience with the MS side and I'm missing an obvious link I should be using, but that URL is giving me a default application page right now:

image

Otherwise, more thoughts on this in general:

I hadn't decided which direction I was going to go with this exiletools-trade-search project - whether to roll it into the main indexer project, or keep it separate, etc. I've heard recently from a couple others who are working on front ends, so it's entirely possible I will just kill this project and add a very simple example search to the main exiletools-indexer project.

So from that regard, it's not really worth merging all of your work into this project. I'd suggest you maintain it as a separate project so you have full control. I'm working on a new page for exiletools and will include a list of all projects using the indexer, and you can post about it on reddit/r/pathofexiledev to see about getting other community people involved. Should work better that way than if I try to merge in a few different projects. ;)

I'm really excited to see what you have done. Also, if it's ready to go this next week you could end up being positioned to get a fair amount of traffic when the new API's and new players/leagues/etc. hit.

**Comment by Spawnbroker** [comment]
Okay cool, sounds good.  I will close this out and and make my own repo and delete the fork.  I'll keep in contact with you on what I have done and if I feel anything is ready to see yet.

**Comment by trackpete** [comment]
Awesome mate! :D

**Pull request closed without merging**
